### PR TITLE
Add example13: complex geometry via networkx

### PR DESCRIPTION
**Pull request by anton-buyskikh**
Hi @mgbukov, here's an example as you suggested in #234 that might close the issue.

I have an related question though. I was wondering if there's any difference in using `*_basis_1d` vs its counterpart `*_basis_general` in case if we don't add any geometry-based symmetries? It seems to me that `*_basis_1d` should be a child class of `*_basis_general` with predefined symmetries in 1D, but I didn't managed to see it after a quick code review. Is there something I should be aware while switching between those two?

### CODE REVIEW

**Comment by anton-buyskikh** [comment]
Issue #243 relates to my question.

**Comment by mgbukov** [comment]
Hi Anton,

1) thanks for setting up this example; I checked that it runs. I also redirected the pull request into the `user_basis` branch which is the current working branch (the `master` will get all updates once we make sure all tests pass). 

a) could you please change the name of the file to `example_18.py` (we wrote a few other examples over the last months to be released with the next update). This will resolve the conflict automatically. 

b) I looked thru your example code, and I have a few suggestions:
- fix the seed (so `nx.draw` returns the same result`)
- add `plt.show()` after `nx,draw(...)` so the user can see the graph
- remove the `checks` (this is for safety, esp with the fermion signs)
- you are currently double-counting the kinetic energy I think: the easiest way out is to only keep the '+-' term (no need for the `-+` term because you loop over all sites and define the adjacent elements)
- add a boundary condition toggler `PBC`, and include it in the graph construction as `periodic=PBC`. 
- use `N` instead of `L` since the linear dimension `L` is not well defined in 2D; also since Lx and Ly do not correspond to the number of sites, I'd choose different names to avoid confusion. 
- if you have time, you may want to double check the energies for PBC against the expressions for the graphene dispersion (to make sure all numbers come out right). This can be done by setting `U=0.0`. For this, u'd need the precise momentum quantization condition as a function of the system size. 

2. the main difference between `basis_1d` and `basis_general` is the way the symmetries are handled: `basis_1d` is faster because all symmetries are pre-coded, while `basis_general` infers them from the symmetry transformations which can be general (general means less efficient, i.e. slower). Also, the `basis_1d` allows you to combine finite-momentum sectors with parity symmetry (the two operations do not commute so the `general_basis` can't do this). 

On the technical level, the `basis_1d` core is written in cython, while the `basis_general` core is written in cpp and wrapped to python using cython. This is the fundamental reason why the two are not related by inheritance. 

Part of the inheritance is historical so we are open to suggestion how to improve it in the future.

**Comment by anton-buyskikh** [comment]
Hi Marin,

Thanks for the feedback.

1. I've implemented your suggestions. I can confirm that I'm not double-counting the tunneling, there are just 2 terms for 2 species of fermions and hopping always goes from site `j` to `i`. Also I haven't checked the energies on the hex lattice as it's not my area of physics and don't have a quick reference for it, unfortunately.

2. That's very useful to know. I guess it would not matter which basis is used (`*_1d` or `*_general`) if no symmetries are involved. I'll try to look deeper in the code in the future and maybe even get involved in restructuring.

**Comment by weinbe58** [comment]
@anton-buyskikh 

So what might be useful with these graph programs would be to see if they can give the graph-isomorphisms. It turns out that these isomorphisms can actually be used to generate the symmetries of the graph, however, as far as I know, the general isomorphisms require implementing non-abelian symmetries which `*_general` basis classes can't handle except in some rare cases (quantum numbers commute under the symmetries). Even still, if you can find even just the generators of translation on the graph that would be great!

**Pull request merged**
